version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:

  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
    restart: always

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/foodgram_backend_static
      - media:/app/media
      - ./backend/:/app/
    restart: always

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /foodgram_frontend_static/
    volumes:
      - static:/foodgram_frontend_static

  nginx:
    image: nginx:1.22.1
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/media
    depends_on:
      - frontend
      - backend
    restart: always
