version: '3.3'

volumes:
  pg_data_prod:
  static_volume:
  media:


services:

  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/pg_data
    restart: always

  backend:
    image: tarrim80/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/foodgram_backend_static
      - media:/app/media
    restart: always

  frontend:
    image: tarrim80/foodgram_frontend
    command: cp -r /app/build/. /foodgram_frontend_static/
    volumes:
      - static_volume:/foodgram_frontend_static

  nginx:
    image: nginx:1.22.1
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles
      - media:/media
    depends_on:
      - frontend
      - backend
    restart: always
