# Generated by Django 3.2.3 on 2023-06-10 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230610_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_favorite_list', models.BooleanField(default=False, help_text='Отметьте, чтобы добавить в избранное', verbose_name='В избранном')),
                ('on_shopping_list', models.BooleanField(default=False, help_text='Отметьте, чтобы добавить в список покупок', verbose_name='В списке покупок')),
                ('recipe', models.ForeignKey(help_text='Выберите рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='recipes.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(help_text='Укажите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Связи рецепта',
                'verbose_name_plural': 'Связи рецептов',
                'ordering': ('user', '-recipe'),
                'default_related_name': 'relations',
            },
        ),
        migrations.AddConstraint(
            model_name='reciperelation',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_relations'),
        ),
    ]
