# Generated by Django 3.2.3 on 2023-06-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230610_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperelation',
            old_name='on_favorite_list',
            new_name='is_favorited',
        ),
        migrations.RenameField(
            model_name='reciperelation',
            old_name='on_shopping_list',
            new_name='is_in_shopping_cart',
        ),
    ]
