# Generated by Django 3.2.3 on 2023-06-12 20:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230612_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Определите цвет тега', image_field=None, max_length=18, samples=None, unique=True, verbose_name='Цветовой HEX-код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Наименование тега', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
